# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo 'Hello from busybox' >> /mnt/data/output.txt; sleep 5; done"]
        volumeMounts:
        - mountPath: /mnt/data
          name: local-storage
      - name: multitool
        image: nicolaka/netshoot
        command: ["/bin/sh", "-c", "while true; do cat /mnt/data/output.txt; sleep 5; done"]
        volumeMounts:
        - mountPath: /mnt/data
          name: local-storage
      volumes:
      - name: local-storage
        persistentVolumeClaim:
          claimName: local-pvc

