apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app-{{ .Values.environment }}
  labels:
    app: {{ .Chart.Name }}-app
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.service.port }}
