apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker-{{ .Values.environment }}
  labels:
    app: {{ .Chart.Name }}-worker
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-worker
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          ports:
            - containerPort: {{ .Values.worker.service.port }}
