apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader
  namespace: default
  labels:
    app: log-reader
spec:
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["sh", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: host-log
          mountPath: /host/var/log
          readOnly: true
      volumes:
      - name: host-log
        hostPath:
          path: /var/log
          type: Directory
      tolerations:
      - effect: NoSchedule
        operator: Exists
