apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
      <body>
    <h1>Secure Kubernetes Page!</h1>
        <p>Served via HTTPS</p>
      </body>
    </html>
